Simplify message functions

diff --git a/mrbones b/mrbones
--- a/mrbones
+++ b/mrbones
@@ -14,48 +14,18 @@ SITE_DIR="$WORKING_DIR/$SITE_DIR_NAME"
 
 
 error_message() {
-    local message
-
-    if [ $# -ne 1 ]
-    then
-        echo -e "\e[1m[mrbones]\e[0m  \e[31mERROR: (INTERNAL) incorrect arguments to" \
-                     "\`error_message(message)\`.\e[0m" 1>&2
-        exit 1
-    fi
-
-    message="$1"
-
-    echo -e "\e[1m[mrbones]\e[0m  \e[31mERROR: $message\e[0m" 1>&2
+    echo -e "\e[1m[mrbones]\e[0m  \e[31mERROR: $@\e[0m" 1>&2
 }
 
 
 error() {
-    local message
-
-    if [ $# -ne 1 ]
-    then
-        error_message "(INTERNAL) incorrect arguments to \`error(message)\`."
-        exit 1
-    fi
-
-    message="$1"
-
-    error_message "$message"
+    error_message "$@"
     exit 1
 }
 
 
 info_message() {
-    local message
-
-    if [ $# -ne 1 ]
-    then
-        error "(INTERNAL) incorrect arguments to \`info_message(message)\`."
-    fi
-
-    message=$1
-
-    echo -e "\e[1m[mrbones]\e[0m  \e[32m$message\e[0m" 1>&2
+    echo -e "\e[1m[mrbones]\e[0m  \e[32m$@\e[0m" 1>&2
 }
 
 
@@ -86,15 +56,16 @@ handle_includes() {
         error "(INTERNAL): incorrect arguments to \`handle_includes(src_page_path)\`."
     fi
 
-    page=$1
+    src_page_path=$1
 
-    page_content="$(cat $page)"
-    for include in $(sed -nE 's/@include (.+)/\1/p' $page)
+    page_content="$(cat $src_page_path)"
+    for include in $(sed -nE 's/@include (.+)/\1/p' $src_page_path)
     do
         # Check if include exists.
         if [ ! -f $TEMPLATES_DIR/$include ]
         then
-            error "missing import in '$page': file '$TEMPLATES_DIR/$include' does not exist."
+            error "missing import in '$src_page_path': file '$TEMPLATES_DIR/$include' does not" \
+                "exist."
         fi
 
         # We need to handle includes recursively.
